'use strict';

// Lagged Fibonacci generator (f = xor, j = 32, k = 521) used by GC/Wii discs to
// pad unused areas, and losslessly re-encoded by RVZ's "packing" scheme.
// See docs/WiaAndRvz.md ("RVZ packing" section) in dolphin-emu/dolphin for the
// public algorithm description that this is implemented from.
const BUFFER_WORDS = 521;
const LAG = 32;

class JunkPrng {
  constructor(seed) {
    if (seed.length !== 68) {
      throw new Error(`PRNG seed must be 68 bytes, got ${seed.length}`);
    }
    this.buffer = new Uint32Array(BUFFER_WORDS);
    for (let i = 0; i < 17; i++) {
      this.buffer[i] = seed.readUInt32BE(i * 4);
    }
    for (let i = 17; i < BUFFER_WORDS; i++) {
      const a = this.buffer[i - 17];
      const b = this.buffer[i - 16];
      const c = this.buffer[i - 1];
      this.buffer[i] = (((a << 23) >>> 0) ^ (b >>> 9) ^ c) >>> 0;
    }
    // Every word (including the 17 seed words) needs bits 16-23 replaced by
    // bits 18-25 of itself before being used as output; without this the
    // generated byte stream doesn't match the original junk data.
    for (let i = 0; i < BUFFER_WORDS; i++) {
      const x = this.buffer[i];
      this.buffer[i] = (x & 0xff00ffff) | ((x >>> 2) & 0x00ff0000);
    }
    this.wordIndex = 0;
    // Byte cursor (0-3) within the current word, so partial-word skips/reads
    // stay correctly aligned with the underlying word stream.
    this.byteInWord = 0;
  }

  _advance() {
    const buf = this.buffer;
    for (let i = 0; i < LAG; i++) {
      buf[i] = (buf[i] ^ buf[i + BUFFER_WORDS - LAG]) >>> 0;
    }
    for (let i = LAG; i < BUFFER_WORDS; i++) {
      buf[i] = (buf[i] ^ buf[i - LAG]) >>> 0;
    }
  }

  _nextByte() {
    if (this.wordIndex === 0 && this.byteInWord === 0) {
      this._advance();
    }
    const word = this.buffer[this.wordIndex];
    const shift = 24 - this.byteInWord * 8;
    const byte = (word >>> shift) & 0xff;
    this.byteInWord++;
    if (this.byteInWord === 4) {
      this.byteInWord = 0;
      this.wordIndex++;
      if (this.wordIndex === BUFFER_WORDS) {
        this.wordIndex = 0;
      }
    }
    return byte;
  }

  // Skip `count` bytes of generated output without producing them.
  skipBytes(count) {
    for (let i = 0; i < count; i++) {
      this._nextByte();
    }
  }

  // Generate `size` bytes of junk data.
  generate(size) {
    const out = Buffer.alloc(size);
    for (let i = 0; i < size; i++) {
      out[i] = this._nextByte();
    }
    return out;
  }
}

// Creates a PRNG state ready to immediately output the junk bytes that were
// stored starting at the given seed; the seed already fully encodes the
// generator's state at that exact byte position, so no extra alignment or
// skipping relative to `discOffset` is needed.
function createPrngAt(seed, _discOffset) {
  const prng = new JunkPrng(seed);
  // The generator always runs 4 initial advances before producing output.
  prng._advance();
  prng._advance();
  prng._advance();
  prng._advance();
  return prng;
}

module.exports = { JunkPrng, createPrngAt };
